/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BorrowedBookResponse {
  author?: string;
  id?: number;
  isbn?: string;
  rate?: number;
  returned?: boolean;
  returnedApproved?: boolean;
  title?: string;
}
