/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getFeedbacksByBookId } from '../fn/feedback/get-feedbacks-by-book-id';
import { GetFeedbacksByBookId$Params } from '../fn/feedback/get-feedbacks-by-book-id';
import { registerFeedback } from '../fn/feedback/register-feedback';
import { RegisterFeedback$Params } from '../fn/feedback/register-feedback';

@Injectable({ providedIn: 'root' })
export class FeedbackService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `registerFeedback()` */
  static readonly RegisterFeedbackPath = '/feedbacks/register';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `registerFeedback()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registerFeedback$Response(params: RegisterFeedback$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return registerFeedback(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `registerFeedback$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registerFeedback(params: RegisterFeedback$Params, context?: HttpContext): Observable<number> {
    return this.registerFeedback$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `getFeedbacksByBookId()` */
  static readonly GetFeedbacksByBookIdPath = '/feedbacks/feedbacks/{book-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getFeedbacksByBookId()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFeedbacksByBookId$Response(params: GetFeedbacksByBookId$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return getFeedbacksByBookId(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getFeedbacksByBookId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFeedbacksByBookId(params: GetFeedbacksByBookId$Params, context?: HttpContext): Observable<{
}> {
    return this.getFeedbacksByBookId$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

}
