/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BookRequest } from '../../models/book-request';
import {CommonResponse} from '../../models/common-response';

export interface RegisterBook$Params {
      body: BookRequest
}

export function registerBook(http: HttpClient, rootUrl: string, params: RegisterBook$Params, context?: HttpContext): Observable<StrictHttpResponse<
CommonResponse<number>>> {
  const rb = new RequestBuilder(rootUrl, registerBook.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CommonResponse<number>>;
    })
  );
}

registerBook.PATH = '/books/register';
