spring:
  profiles:
    active: ${PROFILE:dev}
  servlet:
    multipart:
      max-file-size: 70MB
  cors:
    origins: http://localhost:4200
springdoc:
  default-consumes-media-type: application/json
server:
  servlet:
    context-path: /api/v1
