spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: my_schema
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: on
  mail:
    host: smtp.gmail.com
    port: 587
    username: contact.bassem587@gmail.com
    password: wgkgbobtnfdpfsou
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
#  mail:
#    host: localhost
#    port: 1025
#    username: bassem
#    password: bbbb
#    properties:
#      mail:
#        smtp:
#          trust: "*"
#        auth: true
#        starttls:
#          enable: true
#        connectiontimeout: 5000
#        timeout: 3000
#        writetimeout: 5000
application:
  security:
    jwt:
      secret-key: 84b1e1600ad694aad1d1258a7b80a94ded7659a30494485634bef48f64bf3a58
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    upload:
      photos-output-path: ./uploads
server:
  port: 8088