events {}


http {
    server {
        listen 80;
        #root location
        location / {
            root /usr/share/nginx/html/browser;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
        #handle java script | css files with the correct mime type
        location ~ \.(js|css)$ {
            root /usr/share/nginx/html/browser;
            include /etc/nginx/mime.types;
        }
        #catch all location to handle refreshes on any route
        location ~ ^\.+$ {
            root /usr/share/nginx/html/browser;
            index index.html;
            try_files $uri /index.html;
        }
    }
}

