/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Injectable } from '@angular/core';

/**
 * Global configuration
 */
@Injectable({
  providedIn: 'root',
})
export class ApiConfiguration {
  //rootUrl: string = '/api/v1';
  //rootUrl: string = ' http://crunchier-unconcordantly-macie.ngrok-free.dev';
  rootUrl: string = 'http://localhost:8088/api/v1';
  //rootUrl: string = 'https://crunchier-unconcordantly-macie.ngrok-free.dev/api/v1';
}

/**
 * Parameters for `ApiModule.forRoot()`
 */
export interface ApiConfigurationParams {
  rootUrl?: string;
}
